name: dkim-api

services:
  web:
    build:
      context: .
      dockerfile: compose/fast-api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Maps your local project folder to the container
      # This allows for hot-reloading if you enable it
      - ./project:/code
